### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by fys-leo** [xbdxwyh/yolov3_hls#19]
大佬，如果训练自己数据集在fpga实现，该怎么修改呢

**Comment by xbdxwyh** [comment]
我没理解你的问题，1. 如果你说的是训练新数据，然后仅仅在fpga上做部署推理，那么训练新权重然后按照同样的部分做量化、烧录即可。训练新权重的方法可以参考yolo官方给出的脚本。有关fpga部分的代码不需要进行任何改动。  2. 如果你说的是在fpga上实现网络模型的训练，那这部分可能涉及到很多的代码修改，你需要实现片上的反向传播与优化，这时候由于精度问题，梯度的传播可能会造成很大的精度损失，这需要一些技术解决。关于第二部分的其他细节我就不是很了解了。

> 大佬，如果训练自己数据集在fpga实现，该怎么修改呢

**Comment by fys-leo** [comment]
谢谢大佬回答，我是想训练自己数据集然后部署fpga，权重部分处理是按照陈辰那个代码操作吗

**Comment by xbdxwyh** [comment]
> 谢谢大佬回答，我是想训练自己数据集然后部署fpga，权重部分处理是按照陈辰那个代码操作吗

对，只是训练后部署的话，不需要改动什么代码，你只需要重新训练权重，然后按照步骤操作即可。有关训练的部分你可以参考原始yolo的教程。

**Comment by fys-leo** [comment]
我进行第一步操作生成bin权重显示如下错误，大佬知道咋回事么：
First section must be [net] or [network]: Success
darknet: ./src/utils.c:256: error: Assertion `0' failed.
Aborted (core dumped)
